### PR TITLE
Update README.md

### LINKED ISSUE #8: Fix link
The link on the readme file to `file io` does not work

### PR DESCRIPTION
**Pull request by viktoriussuwandi**
fix #8

Hi @Emmo00,
I just trying to help on this issue, please check it out

### CODE REVIEW

**Comment by Emmo00** [comment]
Hello @viktoriussuwandi , you are welcome to this repo.

The mistake was from the initial naming of the folder. Could you fix that?

The folder name is supposed to be `15_File_io` instead of `15_File_oi`.

**Review by Emmo00 — COMMENTED** [review]
Please rename the folder to `15_File_io`. Thanks 😊

**Comment by viktoriussuwandi** [comment]
I will @Emmo00 , no problem :)

**Comment by viktoriussuwandi** [comment]
done @Emmo00 , please re-review

**Review by Emmo00 — APPROVED** [review]

**Pull request merged**
